"""Definice statistických senzorů pro OIG Cloud."""

from typing import Any, Dict

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import PERCENTAGE, EntityCategory, UnitOfEnergy, UnitOfPower

ICON_TIMELINE_VARIANT = "mdi:chart-timeline-variant"

# Seznam statistických senzorů s jejich konfigurací
SENSOR_TYPES_STATISTICS: Dict[str, Dict[str, Any]] = {
    # Základní odběr - medián za posledních 10 minut
    "battery_load_median": {
        "name": "Load Median 10 Minutes",
        "name_cs": "Medián odběru za 10 minut",
        "unit": UnitOfPower.WATT,
        "icon": "mdi:chart-line",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "sampling_minutes": 10,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
        "description": "Medián celkového odběru domácnosti za posledních 10 minut",
    },
    # Víkend vs všední den odběr po časových úsecích
    "load_avg_6_8_weekday": {
        "name": "Average Load 6-8h Weekday",
        "name_cs": "Průměrný odběr 6-8h (všední dny)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (6, 8),
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    "load_avg_8_12_weekday": {
        "name": "Average Load 8-12h Weekday",
        "name_cs": "Průměrný odběr 8-12h (všední dny)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (8, 12),
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    "load_avg_12_16_weekday": {
        "name": "Average Load 12-16h Weekday",
        "name_cs": "Průměrný odběr 12-16h (všední dny)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (12, 16),
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    "load_avg_16_22_weekday": {
        "name": "Average Load 16-22h Weekday",
        "name_cs": "Průměrný odběr 16-22h (všední dny)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (16, 22),
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    "load_avg_22_6_weekday": {
        "name": "Average Load 22-6h Weekday",
        "name_cs": "Průměrný odběr 22-6h (všední dny)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (22, 6),  # přes půlnoc
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    # Víkendové varianty
    "load_avg_6_8_weekend": {
        "name": "Average Load 6-8h Weekend",
        "name_cs": "Průměrný odběr 6-8h (víkendy)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (6, 8),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    "load_avg_8_12_weekend": {
        "name": "Average Load 8-12h Weekend",
        "name_cs": "Průměrný odběr 8-12h (víkendy)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (8, 12),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    "load_avg_12_16_weekend": {
        "name": "Average Load 12-16h Weekend",
        "name_cs": "Průměrný odběr 12-16h (víkendy)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (12, 16),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 500,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    "load_avg_16_22_weekend": {
        "name": "Average Load 16-22h Weekend",
        "name_cs": "Průměrný odběr 16-22h (víkendy)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (16, 22),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    "load_avg_22_6_weekend": {
        "name": "Average Load 22-6h Weekend",
        "name_cs": "Průměrný odběr 22-6h (víkendy)",
        "unit": UnitOfPower.WATT,
        "icon": ICON_TIMELINE_VARIANT,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "time_range": (22, 6),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 14,
        "sampling_size": 1000,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
    },
    # Predikční senzory - ODSTRANĚNO: battery_prediction_discharge_time, battery_prediction_needed_capacity, battery_prediction_morning_soc
    # Tyto senzory byly nahrazeny battery_forecast sensorem
    # Hodinové reálné senzory - používají existující computed energy senzory
    "hourly_real_battery_charge_kwh": {
        "name": "Hourly Battery Charge",
        "name_cs": "Hodinové nabíjení baterie",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
        "hourly_data_type": "energy_diff",
        "source_sensor": "computed_batt_charge_energy_today",
        "description": "Reálné nabíjení baterie za poslední hodinu",
    },
    "hourly_real_battery_discharge_kwh": {
        "name": "Hourly Battery Discharge",
        "name_cs": "Hodinové vybíjení baterie",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
        "hourly_data_type": "energy_diff",
        "source_sensor": "computed_batt_discharge_energy_today",
        "description": "Reálné vybíjení baterie za poslední hodinu",
    },
    "hourly_real_fve_total_kwh": {
        "name": "Hourly FVE Production",
        "name_cs": "Hodinová výroba FVE",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "icon": "mdi:solar-power",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
        "hourly_data_type": "power_integral",
        "source_sensor": "actual_fv_total",
        "description": "Reálná celková výroba FVE za poslední hodinu",
    },
    "hourly_real_load_kwh": {
        "name": "Hourly Load Consumption",
        "name_cs": "Hodinová spotřeba zátěže",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "icon": "mdi:home-lightning-bolt",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
        "hourly_data_type": "power_integral",
        "source_sensor": "actual_aco_p",
        "description": "Reálná spotřeba za poslední hodinu",
    },
    "hourly_real_boiler_kwh": {
        "name": "Hourly Boiler Consumption",
        "name_cs": "Hodinová spotřeba bojleru",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "icon": "mdi:water-boiler",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
        "hourly_data_type": "energy_diff",
        "source_sensor": "boiler_day_w",
        "description": "Reálná spotřeba bojleru za poslední hodinu",
    },
    # Hodinové FVE stringy
    "hourly_real_fve_string_1_kwh": {
        "name": "Hourly FVE String 1 Production",
        "name_cs": "Hodinová výroba FVE string 1",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "icon": "mdi:solar-panel",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
        "hourly_data_type": "power_integral",
        "source_sensor": "actual_fv_p1",
        "description": "Reálná výroba FVE string 1 za poslední hodinu",
    },
    "hourly_real_fve_string_2_kwh": {
        "name": "Hourly FVE String 2 Production",
        "name_cs": "Hodinová výroba FVE string 2",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "icon": "mdi:solar-panel",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "statistics",
        "device_mapping": "analytics",
        "hourly_data_type": "power_integral",
        "source_sensor": "actual_fv_p2",
        "description": "Reálná výroba FVE string 2 za poslední hodinu",
    },
    # ====================================================================================
    # OPTIMALIZACE NABÍJENÍ BATERIE - Rozděleno podle 3 hlavních cílů
    # ====================================================================================
    # 🎯 CÍL 1: AUTOMATIZACE NABÍJENÍ - Senzory pro automatizační pravidla
    # ====================================================================================
    # Hlavní predikční senzor - KAPACITA BATERIE V PRŮBĚHU DNE
    "battery_forecast": {
        "name": "Battery Capacity Forecast",
        "name_cs": "Predikce kapacity baterie",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "icon": "mdi:battery-charging-80",
        "device_class": SensorDeviceClass.ENERGY_STORAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "sensor_type_category": "battery_prediction",
        "device_mapping": "analytics",  # Hlavní senzor - vytváří OigCloudBatteryForecastSensor
        "entity_category": EntityCategory.DIAGNOSTIC,
        "description": "Aktuální predikovaná kapacita baterie (kWh). Atributy obsahují kompletní timeline predikce.",
    },
    "planner_recommended_mode": {
        "name": "Planner Recommended Mode",
        "name_cs": "Doporučený režim (plánovač)",
        "unit": None,
        "icon": "mdi:robot",
        "device_class": None,
        "state_class": None,
        "sensor_type_category": "planner_status",
        "device_mapping": "analytics",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "description": "Doporučený režim pro aktuální interval z hybrid plánovače (např. Home 1/Home UPS) + informace o příští změně.",
    },
    "battery_balancing": {
        "name": "Battery Balancing Status",
        "name_cs": "Stav vyrovnání baterie",
        "unit": None,
        "icon": "mdi:battery-heart-variant",
        "device_class": None,
        "state_class": None,
        "sensor_type_category": "battery_balancing",
        "device_mapping": "analytics",  # Specializovaný senzor pro battery balancing
        "entity_category": EntityCategory.DIAGNOSTIC,
        "description": "Stav vyrovnání článků baterie. Zobrazuje kdy bylo poslední vyrovnání, kolik dní uplynulo, zda je naplánováno další a předpokládané náklady.",
    },
    "grid_charging_planned": {
        "name": "Grid Charging Planned",
        "name_cs": "Plánované nabíjení ze sítě",
        "unit": None,  # Binary sensor (on/off)
        "icon": "mdi:battery-charging",
        "device_class": None,  # Binary sensor bez device class
        "state_class": None,  # Binary sensor nemá state class
        "sensor_type_category": "grid_charging_plan",
        "device_mapping": "analytics",  # Specializovaný senzor
        "entity_category": None,  # Hlavní senzor, ne diagnostic
        "description": "Indikátor plánovaného nabíjení baterie ze sítě (on/off). Atributy obsahují intervaly nabíjení, celkovou energii (kWh) a cenu (Kč).",
    },
    "battery_efficiency": {
        "name": "Battery Efficiency",
        "name_cs": "Efektivita baterie (měsíc)",
        "unit": PERCENTAGE,
        "icon": "mdi:battery-sync",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "sensor_type_category": "battery_efficiency",
        "device_mapping": "analytics",
        "entity_category": None,
        "description": "Round-trip efektivita baterie za minulý kompletní měsíc (%). Atributy obsahují průběžná data aktuálního měsíce a detailní metriky.",
    },
    "adaptive_load_profiles": {
        "name": "Adaptive Load Profiles",
        "name_cs": "Adaptivní profily spotřeby",
        "unit": None,  # State = počet profilů
        "icon": "mdi:chart-timeline-variant-shimmer",
        "device_class": None,
        "state_class": None,
        "sensor_type_category": "adaptive_profiles",
        "device_mapping": "analytics",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "description": "Automaticky generované profily spotřeby založené na historických datech. State = počet profilů, attributes = detaily jednotlivých profilů.",
    },
    "forecast_accuracy": {
        "name": "Forecast Accuracy",
        "name_cs": "Přesnost předpovědi",
        "unit": "%",
        "icon": "mdi:target-variant",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "sensor_type_category": "forecast_accuracy",
        "device_mapping": "analytics",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "description": "Jak přesně denní plán trefil skutečnost. State = průměrná chyba spotřeby za 7 dní (%), attributes = rozpad po dnech, po verzích plánu, proti naivní predikci a v Kč.",
    },
}
