// AUTO-GENERATED (codegen) — real MDI icon paths for the tile icon picker.
// Maps the picker's kebab names to @mdi/js path data. Tree-shaken: only these import.
import {
  mdiAccessPoint,
  mdiAccount,
  mdiAirConditioner,
  mdiAirFilter,
  mdiAirPurifier,
  mdiAirplane,
  mdiAlarm,
  mdiAlarmLight,
  mdiAlertCircle,
  mdiArrowDown,
  mdiArrowUp,
  mdiBalcony,
  mdiBasket,
  mdiBathtub,
  mdiBattery,
  mdiBattery10,
  mdiBattery50,
  mdiBatteryCharging,
  mdiBell,
  mdiBellRing,
  mdiBicycle,
  mdiBlender,
  mdiBlinds,
  mdiBlindsOpen,
  mdiBluetooth,
  mdiBrightness5,
  mdiBrightness7,
  mdiBroom,
  mdiBus,
  mdiCalendar,
  mdiCalendarClock,
  mdiCamera,
  mdiCar,
  mdiCarBattery,
  mdiCarElectric,
  mdiCast,
  mdiCctv,
  mdiCeilingLight,
  mdiCellphone,
  mdiChandelier,
  mdiChartLine,
  mdiCheck,
  mdiCheckboxMarkedCircle,
  mdiClock,
  mdiClose,
  mdiCloud,
  mdiCash,
  mdiCoffeeMaker,
  mdiCog,
  mdiContentCut,
  mdiCurrentAc,
  mdiCurrentDc,
  mdiCurtains,
  mdiDeskLamp,
  mdiDishwasher,
  mdiDoor,
  mdiDoorOpen,
  mdiDoorSliding,
  mdiDotsVertical,
  mdiEthernet,
  mdiEvPlugType2,
  mdiEvStation,
  mdiEye,
  mdiFan,
  mdiFaucet,
  mdiFingerprint,
  mdiFire,
  mdiFireplace,
  mdiFlash,
  mdiFloorLamp,
  mdiFlower,
  mdiFridge,
  mdiFridgeOutline,
  mdiGamepad,
  mdiGarage,
  mdiGarageOpen,
  mdiGauge,
  mdiGrass,
  mdiGrill,
  mdiHammer,
  mdiHanger,
  mdiHeadphones,
  mdiHeatPump,
  mdiHeatingCoil,
  mdiHelpCircle,
  mdiHistory,
  mdiHome,
  mdiHomeAssistant,
  mdiHotTub,
  mdiHvac,
  mdiInformation,
  mdiIron,
  mdiKettle,
  mdiKey,
  mdiLamp,
  mdiLan,
  mdiLaptop,
  mdiLedStrip,
  mdiLedStripVariant,
  mdiLightSwitch,
  mdiLightbulb,
  mdiLightbulbOutline,
  mdiLightningBolt,
  mdiPencil,
  mdiLock,
  mdiLockOpen,
  mdiLogout,
  mdiMenu,
  mdiMeterElectric,
  mdiMicrophone,
  mdiMicrowave,
  mdiMinus,
  mdiMoleculeCo2,
  mdiMotionSensor,
  mdiMotorbike,
  mdiMovie,
  mdiMusic,
  mdiNas,
  mdiNetwork,
  mdiOutdoorLamp,
  mdiPause,
  mdiPipe,
  mdiPlay,
  mdiPlus,
  mdiPool,
  mdiPot,
  mdiPotSteam,
  mdiPotSteamOutline,
  mdiPower,
  mdiPowerPlug,
  mdiPowerSocket,
  mdiRadiator,
  mdiRadiatorDisabled,
  mdiRadio,
  mdiRefresh,
  mdiRollerShade,
  mdiRouterWireless,
  mdiScooter,
  mdiServer,
  mdiShieldCheck,
  mdiShieldHome,
  mdiShower,
  mdiSkipNext,
  mdiSkipPrevious,
  mdiSmokeDetector,
  mdiSnowflake,
  mdiSolarPanel,
  mdiSolarPower,
  mdiSpeaker,
  mdiSpeakerWireless,
  mdiSpotify,
  mdiSpotlight,
  mdiSprinkler,
  mdiStop,
  mdiStove,
  mdiSync,
  mdiTablet,
  mdiTelevision,
  mdiThermometer,
  mdiThermometerLines,
  mdiThermostat,
  mdiTimer,
  mdiToaster,
  mdiToasterOven,
  mdiToggleSwitch,
  mdiToilet,
  mdiTools,
  mdiTrain,
  mdiTransmissionTower,
  mdiTree,
  mdiTumbleDryer,
  mdiUmbrella,
  mdiVacuum,
  mdiVolumeHigh,
  mdiVolumeLow,
  mdiWallSconce,
  mdiWashingMachine,
  mdiWater,
  mdiWaterBoiler,
  mdiWaterPercent,
  mdiWaterPump,
  mdiWeatherCloudy,
  mdiWeatherFog,
  mdiWeatherHail,
  mdiWeatherLightning,
  mdiWeatherLightningRainy,
  mdiWeatherNight,
  mdiWeatherPartlyCloudy,
  mdiWeatherPartlyRainy,
  mdiWeatherPouring,
  mdiWeatherRainy,
  mdiWeatherSnowy,
  mdiWeatherSnowyRainy,
  mdiWeatherSunny,
  mdiWeatherWindy,
  mdiWeatherWindyVariant,
  mdiWifi,
  mdiWindTurbine,
  mdiWindowClosed,
  mdiWindowOpen,
  mdiWindowShutter,
  mdiWrench,
} from '@mdi/js';

export const MDI_ICON_PATHS: Record<string, string> = {
  'fridge': mdiFridge,
  'fridge-outline': mdiFridgeOutline,
  'dishwasher': mdiDishwasher,
  'washing-machine': mdiWashingMachine,
  'tumble-dryer': mdiTumbleDryer,
  'stove': mdiStove,
  'microwave': mdiMicrowave,
  'coffee-maker': mdiCoffeeMaker,
  'kettle': mdiKettle,
  'toaster': mdiToaster,
  'blender': mdiBlender,
  'food-processor': mdiBlender,
  'rice-cooker': mdiPotSteam,
  'slow-cooker': mdiPotSteamOutline,
  'pressure-cooker': mdiPot,
  'air-fryer': mdiToasterOven,
  'oven': mdiToasterOven,
  'range-hood': mdiAirFilter,
  'lightbulb': mdiLightbulb,
  'lightbulb-outline': mdiLightbulbOutline,
  'lamp': mdiLamp,
  'ceiling-light': mdiCeilingLight,
  'floor-lamp': mdiFloorLamp,
  'led-strip': mdiLedStrip,
  'led-strip-variant': mdiLedStripVariant,
  'wall-sconce': mdiWallSconce,
  'chandelier': mdiChandelier,
  'desk-lamp': mdiDeskLamp,
  'spotlight': mdiSpotlight,
  'light-switch': mdiLightSwitch,
  'thermometer': mdiThermometer,
  'thermostat': mdiThermostat,
  'radiator': mdiRadiator,
  'radiator-disabled': mdiRadiatorDisabled,
  'heat-pump': mdiHeatPump,
  'air-conditioner': mdiAirConditioner,
  'fan': mdiFan,
  'hvac': mdiHvac,
  'fire': mdiFire,
  'snowflake': mdiSnowflake,
  'fireplace': mdiFireplace,
  'heating-coil': mdiHeatingCoil,
  'lightning-bolt': mdiLightningBolt,
  'flash': mdiFlash,
  'pencil': mdiPencil,
  'battery': mdiBattery,
  'battery-charging': mdiBatteryCharging,
  'battery-50': mdiBattery50,
  'battery-10': mdiBattery10,
  'solar-panel': mdiSolarPanel,
  'solar-power': mdiSolarPower,
  'meter-electric': mdiMeterElectric,
  'power-plug': mdiPowerPlug,
  'power-socket': mdiPowerSocket,
  'ev-plug': mdiEvStation,
  'transmission-tower': mdiTransmissionTower,
  'current-ac': mdiCurrentAc,
  'current-dc': mdiCurrentDc,
  'car': mdiCar,
  'car-electric': mdiCarElectric,
  'car-battery': mdiCarBattery,
  'ev-station': mdiEvStation,
  'ev-plug-type2': mdiEvPlugType2,
  'garage': mdiGarage,
  'garage-open': mdiGarageOpen,
  'motorcycle': mdiMotorbike,
  'bicycle': mdiBicycle,
  'scooter': mdiScooter,
  'bus': mdiBus,
  'train': mdiTrain,
  'airplane': mdiAirplane,
  'door': mdiDoor,
  'door-open': mdiDoorOpen,
  'lock': mdiLock,
  'lock-open': mdiLockOpen,
  'shield-home': mdiShieldHome,
  'cctv': mdiCctv,
  'camera': mdiCamera,
  'motion-sensor': mdiMotionSensor,
  'alarm-light': mdiAlarmLight,
  'bell': mdiBell,
  'eye': mdiEye,
  'key': mdiKey,
  'fingerprint': mdiFingerprint,
  'shield-check': mdiShieldCheck,
  'window-closed': mdiWindowClosed,
  'window-open': mdiWindowOpen,
  'blinds': mdiBlinds,
  'blinds-open': mdiBlindsOpen,
  'curtains': mdiCurtains,
  'roller-shade': mdiRollerShade,
  'window-shutter': mdiWindowShutter,
  'balcony': mdiBalcony,
  'door-sliding': mdiDoorSliding,
  'television': mdiTelevision,
  'speaker': mdiSpeaker,
  'speaker-wireless': mdiSpeakerWireless,
  'music': mdiMusic,
  'volume-high': mdiVolumeHigh,
  'cast': mdiCast,
  'chromecast': mdiCast,
  'radio': mdiRadio,
  'headphones': mdiHeadphones,
  'microphone': mdiMicrophone,
  'gamepad': mdiGamepad,
  'movie': mdiMovie,
  'spotify': mdiSpotify,
  'router-wireless': mdiRouterWireless,
  'wifi': mdiWifi,
  'access-point': mdiAccessPoint,
  'lan': mdiLan,
  'network': mdiNetwork,
  'home-assistant': mdiHomeAssistant,
  'server': mdiServer,
  'nas': mdiNas,
  'cloud': mdiCloud,
  'ethernet': mdiEthernet,
  'bluetooth': mdiBluetooth,
  'cellphone': mdiCellphone,
  'tablet': mdiTablet,
  'laptop': mdiLaptop,
  'water': mdiWater,
  'water-percent': mdiWaterPercent,
  'water-boiler': mdiWaterBoiler,
  'water-pump': mdiWaterPump,
  'shower': mdiShower,
  'toilet': mdiToilet,
  'faucet': mdiFaucet,
  'pipe': mdiPipe,
  'bathtub': mdiBathtub,
  'sink': mdiFaucet,
  'water-heater': mdiWaterBoiler,
  'pool': mdiPool,
  'weather-sunny': mdiWeatherSunny,
  'weather-cloudy': mdiWeatherCloudy,
  'weather-night': mdiWeatherNight,
  'weather-rainy': mdiWeatherRainy,
  'weather-snowy': mdiWeatherSnowy,
  'weather-windy': mdiWeatherWindy,
  'weather-fog': mdiWeatherFog,
  'weather-lightning': mdiWeatherLightning,
  'weather-lightning-rainy': mdiWeatherLightningRainy,
  'weather-hail': mdiWeatherHail,
  'weather-partly-cloudy': mdiWeatherPartlyCloudy,
  'weather-partly-rainy': mdiWeatherPartlyRainy,
  'weather-pouring': mdiWeatherPouring,
  'weather-snowy-rainy': mdiWeatherSnowyRainy,
  'weather-windy-variant': mdiWeatherWindyVariant,
  'temperature': mdiThermometer,
  'humidity': mdiWaterPercent,
  'barometer': mdiGauge,
  'air-filter': mdiAirFilter,
  'air-purifier': mdiAirPurifier,
  'smoke-detector': mdiSmokeDetector,
  'co2': mdiMoleculeCo2,
  'wind-turbine': mdiWindTurbine,
  'flower': mdiFlower,
  'tree': mdiTree,
  'sprinkler': mdiSprinkler,
  'grass': mdiGrass,
  'garden-light': mdiOutdoorLamp,
  'outdoor-lamp': mdiOutdoorLamp,
  'grill': mdiGrill,
  'hot-tub': mdiHotTub,
  'umbrella': mdiUmbrella,
  'thermometer-lines': mdiThermometerLines,
  'iron': mdiIron,
  'vacuum': mdiVacuum,
  'broom': mdiBroom,
  'mop': mdiBroom,
  'washing': mdiWashingMachine,
  'basket': mdiBasket,
  'hanger': mdiHanger,
  'scissors': mdiContentCut,
  'information': mdiInformation,
  'help-circle': mdiHelpCircle,
  'alert-circle': mdiAlertCircle,
  'checkbox-marked-circle': mdiCheckboxMarkedCircle,
  'check': mdiCheck,
  'close': mdiClose,
  'minus': mdiMinus,
  'plus': mdiPlus,
  'arrow-up': mdiArrowUp,
  'arrow-down': mdiArrowDown,
  'refresh': mdiRefresh,
  'sync': mdiSync,
  'bell-ring': mdiBellRing,
  'toggle-switch': mdiToggleSwitch,
  'power': mdiPower,
  'play': mdiPlay,
  'pause': mdiPause,
  'stop': mdiStop,
  'skip-next': mdiSkipNext,
  'skip-previous': mdiSkipPrevious,
  'volume-up': mdiVolumeHigh,
  'volume-down': mdiVolumeLow,
  'brightness-up': mdiBrightness7,
  'brightness-down': mdiBrightness5,
  'clock': mdiClock,
  'timer': mdiTimer,
  'alarm': mdiAlarm,
  'calendar': mdiCalendar,
  'calendar-clock': mdiCalendarClock,
  'schedule': mdiCalendarClock,
  'history': mdiHistory,
  'home': mdiHome,
  'cog': mdiCog,
  'tools': mdiTools,
  'wrench': mdiWrench,
  'hammer': mdiHammer,
  'chart-line': mdiChartLine,
  'cash': mdiCash,
  'gauge': mdiGauge,
  'dots-vertical': mdiDotsVertical,
  'menu': mdiMenu,
  'settings': mdiCog,
  'account': mdiAccount,
  'logout': mdiLogout,
};

/** Path data for an mdi icon name (with or without 'mdi:' prefix), or '' if unknown. */
export function mdiIconPath(name: string): string {
  if (!name) return '';
  return MDI_ICON_PATHS[name.replace(/^mdi:/, '')] || '';
}
